name: Assign Issues

on:
  issues:
    types: [opened, reopened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Explicit permission to modify issues
    steps:
    - name: Assign issue to maintainers
      uses: actions-ecosystem/action-add-assignee@v1
      with:
        assignees: |
          konk32
          maskedman27
        add_method: rotate  # Alternates between assignees
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for authentication
