name: Assign Issues

on:
  issues:
    types: [opened, reopened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Required to assign issues
    steps:
    - name: Assign issue to maintainers
      uses: peter-evans/auto-assign-action@v2
      with:
        assignees: |
          konk32
          maskedman27
        add_method: rotate  # Alternates between assignees
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for authentication
