name: Assign Issues

on:
  issues:
    types: [opened, reopened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Explicit permission needed
    steps:
    - name: Assign issue
      uses: actions/github-script@v6
      with:
        script: |
          const maintainers = ['konk32', 'maskedman27'];
          const assignee = maintainers[context.issue.number % 2];
          await github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            assignees: [assignee]
          });
